---
mode: 'train'
gpu: True
resume_checkpoint: "/home/yandex/APDL2526a/sapirtalmi/mellow_apdl_project/outputs/2026-03-31_10-38-33/model--epo-7.ckpt"

data:
    datapath: '/home/yandex/APDL2526a/idantarshish/mellow_apdl_project/data'
    datafiles:
        - '/home/yandex/APDL2526a/sapirtalmi/mellow_apdl_project/datafiles/train_clotho.json'
    val_datafiles:
        - '/home/yandex/APDL2526a/sapirtalmi/mellow_apdl_project/datafiles/val_clotho.json'
    sampling_rate: 32000
    segment_seconds: 10
    tokenizer_type: "HuggingFaceTB/SmolLM2-135M"
    op_text_len: 250
    ip_text_len: 129

model:
    encoder:
        audioenc_name: 'HTSAT'
        transformer_embed_dim: 768
        out_emb: 768
        d_proj: 576
        use_pretrained_audioencoder: True
        freeze_audio_encoder_weights: True
        pretrained_audioencoder_path: '/home/yandex/APDL2526a/sapirtalmi/mellow_apdl_project/htsat'
    decoder:
        text_decoder: "HuggingFaceTB/SmolLM2-135M"
        prefix_length: 40
        total_prefix_length: 389
        freeze_gpt_weights: False
    model_type: Mellow
    input_channels: 1
    output_channels: 1
    resume_checkpoint: ""
    inference_window: 5

train:
    optimizer:
        optimizer_type: Adam
        learning_rate: 5e-5
        warm_up_steps: 10000
        reduce_lr_steps: 1000000
        weight_decay: 0.0001
        scheduler: "cosine"
    max_grad_norm: 0.5
    emergency_stop_grad_norm: 1e6
    num_nodes: 1
    num_workers: 2
    persistent_data_workers: True
    loss_type: sisdr_wav
    sync_batchnorm: False
    batch_size: 2
    num_epochs: 10
    log_step: 100
    sav_per_num_epochs: 1
    random_seed: 1234
    mixed_precision:
        use_mixed_precision: False
        mixed_precision_dtype: "float16"
